name: 'Build-.testing-prerequisites'
description: 'Build pre-requisites for .testing including FMS and a symmetric MOM6 executable'
runs:
  using: 'composite'
  steps:
    - name: Git info
      shell: bash
      run: |
        echo "::group::Git commit info"
        echo "git log:"
        git log | head -60
        echo "::endgroup::"

    - name: Env
      shell: bash
      run: |
        echo "::group::Environment"
        env
        echo "::endgroup::"

    - name: Install needed packages for compiling
      shell: bash
      run: |
        echo "::group::Install linux packages"
        sudo apt-get install netcdf-bin libnetcdf-dev libnetcdff-dev mpich libmpich-dev
        echo "::endgroup::"

    - name: Compile FMS library
      shell: bash
      run: |
        echo "::group::Compile FMS library"
        cd .testing
        make deps/lib/libFMS.a -s -j
        echo "::endgroup::"

    - name: Compile MOM6 in symmetric memory mode
      shell: bash
      run: |
        echo "::group::Compile MOM6 in symmetric memory mode"
        cd .testing
        make build/symmetric/MOM6 -j
        echo "::endgroup::"

    - name: Install local python venv for generating input data
      shell: bash
      run: |
        echo "::group::Create local python env for input data generation"
        cd .testing
        make work/local-env
        echo "::endgroup::"

    - name: Set flags
      shell: bash
      run: |
        echo "FC_TEST_VAR=yellow green blue" >> $GITHUB_ENV

