# GenerateGSWCMake.cmake - Generate CMakeLists.txt for GSW-Fortran submodule
#
# This generates a CMakeLists.txt at configure time for older GSW-Fortran
# versions that don't have CMake support. Can be removed once the submodule
# is updated to a version with native CMake support.

set(GSW_DIR "${CMAKE_SOURCE_DIR}/pkg/GSW-Fortran")

# Only generate if CMakeLists.txt doesn't exist (allows native cmake to work)
if(NOT EXISTS "${GSW_DIR}/CMakeLists.txt")
  message(STATUS "Generating CMakeLists.txt for GSW-Fortran (submodule lacks CMake support)")

  file(WRITE "${GSW_DIR}/CMakeLists.txt" [=[
# Auto-generated by MOM6 CMake build system
# GSW-Fortran - TEOS-10 Gibbs SeaWater Oceanographic Toolbox

cmake_minimum_required(VERSION 3.12)
project(GSW-Fortran LANGUAGES Fortran)

add_library(gsw STATIC)
add_library(GSW::gsw ALIAS gsw)

set(GSW_MOD_DIR "${CMAKE_CURRENT_BINARY_DIR}/mod")
set_target_properties(gsw PROPERTIES
  Fortran_MODULE_DIRECTORY "${GSW_MOD_DIR}"
  POSITION_INDEPENDENT_CODE ON
)

target_include_directories(gsw PUBLIC
  $<BUILD_INTERFACE:${GSW_MOD_DIR}>
  $<INSTALL_INTERFACE:include/gsw>
)

target_sources(gsw PRIVATE
  ${CMAKE_CURRENT_SOURCE_DIR}/modules/gsw_mod_kinds.f90
  ${CMAKE_CURRENT_SOURCE_DIR}/modules/gsw_mod_teos10_constants.f90
  ${CMAKE_CURRENT_SOURCE_DIR}/modules/gsw_mod_specvol_coefficients.f90
  ${CMAKE_CURRENT_SOURCE_DIR}/modules/gsw_mod_freezing_poly_coefficients.f90
  ${CMAKE_CURRENT_SOURCE_DIR}/modules/gsw_mod_gibbs_ice_coefficients.f90
  ${CMAKE_CURRENT_SOURCE_DIR}/modules/gsw_mod_sp_coefficients.f90
  ${CMAKE_CURRENT_SOURCE_DIR}/modules/gsw_mod_baltic_data.f90
  ${CMAKE_CURRENT_SOURCE_DIR}/modules/gsw_mod_saar_data.f90
  ${CMAKE_CURRENT_SOURCE_DIR}/modules/gsw_mod_error_functions.f90
  ${CMAKE_CURRENT_SOURCE_DIR}/modules/gsw_mod_netcdf.f90
  ${CMAKE_CURRENT_SOURCE_DIR}/modules/gsw_mod_toolbox.f90
)

file(GLOB GSW_TOOLBOX_SOURCES "${CMAKE_CURRENT_SOURCE_DIR}/toolbox/*.f90")
target_sources(gsw PRIVATE ${GSW_TOOLBOX_SOURCES})

if(TARGET NetCDF::NetCDF_Fortran)
  target_link_libraries(gsw PUBLIC NetCDF::NetCDF_Fortran)
endif()

# Install as part of MOM6 export set
include(GNUInstallDirs)
install(TARGETS gsw
  EXPORT MOM6Targets
  LIBRARY DESTINATION ${CMAKE_INSTALL_LIBDIR}
  ARCHIVE DESTINATION ${CMAKE_INSTALL_LIBDIR}
)
install(DIRECTORY ${GSW_MOD_DIR}/
  DESTINATION ${CMAKE_INSTALL_INCLUDEDIR}/gsw
  FILES_MATCHING PATTERN "*.mod"
)
]=])
endif()
