#!/usr/bin/env python3
"""Generate lookup tables for MOM_log_data_n128.F90.

This script documents and regenerates a log_repro lookup table using the
table-reduction strategy described in MOM_log_data_n128.F90:

  * cover the factor-of-two interval [11/16, 22/16),
  * divide one positive-normal binary64 exponent stride into 128 equal bins in
    the ordered floating-point bit grid,
  * choose log(c) on a 2**-43 grid near each nominal bin center,
  * derive c = exp(log(c)), invc = 1/c, and a high/low split of c.

The default search rule chooses the nearest 2**-43 log(c) grid point to the
nominal bin-center logarithm.  Use --search-radius and --objective to explore
nearby grid points explicitly.

The generated tables are printed to stdout as a complete Fortran module.
"""

from __future__ import annotations

import argparse
import math
import struct
from decimal import Decimal, ROUND_HALF_EVEN, getcontext


LOG_NDIV = 128
LOG_TABLE_START = 0.6875
EXP_STRIDE = 2**52
LOGC_GRID = Decimal(2) ** -43


def float_to_bits(x: float) -> int:
    """Return the binary64 bit pattern of x as an unsigned integer."""

    return struct.unpack(">Q", struct.pack(">d", x))[0]


def bits_to_float(xb: int) -> float:
    """Return the binary64 value represented by xb."""

    return struct.unpack(">d", struct.pack(">Q", xb))[0]


def nearest_integer(x: Decimal) -> int:
    """Return the nearest integer to x, with ties to even."""

    return int(x.to_integral_value(rounding=ROUND_HALF_EVEN))


def nominal_center(j: int) -> Decimal:
    """Return the nominal c value at the center of table bin j."""

    start_bits = float_to_bits(LOG_TABLE_START)
    step_bits = EXP_STRIDE // LOG_NDIV
    center_bits = start_bits + j * step_bits + step_bits // 2
    return Decimal.from_float(bits_to_float(center_bits))


def split_high_low(c: Decimal) -> tuple[float, float]:
    """Split c into a binary64 high part and residual low part."""

    chi = float(c)
    clo = float(c - Decimal.from_float(chi))
    return chi, clo


def choose_logc(c0: Decimal, search_radius: int, objective: str) -> Decimal:
    """Choose log(c) on the 2**-43 grid near the nominal bin center."""

    logc0 = getcontext().ln(c0)
    q0 = nearest_integer(logc0 / LOGC_GRID)

    best_q = q0
    best_score = None
    for q in range(q0 - search_radius, q0 + search_radius + 1):
        logc = Decimal(q) * LOGC_GRID
        c = getcontext().exp(logc)
        chi, clo = split_high_low(c)

        if objective == "nearest-log":
            score = abs(logc - logc0)
        elif objective == "nearest-c":
            score = abs(c - c0)
        elif objective == "nearest-chi":
            score = abs(Decimal.from_float(chi) - c0)
        elif objective == "smallest-clo":
            score = abs(Decimal.from_float(clo))
        else:
            raise ValueError(f"unknown objective {objective!r}")

        if best_score is None or score < best_score:
            best_score = score
            best_q = q

    return Decimal(best_q) * LOGC_GRID


def generate_tables(search_radius: int, objective: str):
    """Generate log table arrays."""

    invc = []
    logc = []
    chi = []
    clo = []

    for j in range(LOG_NDIV):
        c0 = nominal_center(j)
        logcj = choose_logc(c0, search_radius, objective)
        cj = getcontext().exp(logcj)
        chij, cloj = split_high_low(cj)

        logc.append(float(logcj))
        invc.append(float(1 / cj))
        chi.append(chij)
        clo.append(cloj)

    return invc, logc, chi, clo


def format_array(name: str, values: list[float], comment: str) -> str:
    """Return a Fortran parameter array definition."""

    lines = [comment]
    lines.append(f"real, parameter :: {name}(0:log_ndiv-1) = [ &")
    for i in range(0, len(values), 4):
        chunk = values[i : i + 4]
        suffix = ", &" if i + 4 < len(values) else " &"
        body = ", ".join(f"{v: .17e}" for v in chunk)
        lines.append(f"    {body}{suffix}")
    lines.append("]")
    return "\n".join(lines)


def print_module(invc, logc, chi, clo, objective: str, search_radius: int):
    """Print a complete Fortran table module."""

    print("! This file is part of MOM6, the Modular Ocean Model version 6.")
    print("! See the LICENSE file for licensing information.")
    print("! SPDX-License-Identifier: Apache-2.0")
    print()
    print("!> Lookup tables for the reproducible log() function, assuming real64 precision.")
    print("!! Generated by generate_MOM_log_data_n128.py.")
    print(f"!! log(c) search objective: {objective}; search radius: {search_radius} grid steps.")
    print("module MOM_log_data_n128")
    print()
    print("implicit none ; private")
    print()
    print("public :: log_ndiv, log_table_start")
    print("public :: log_invc_lookup, logc_lookup, log_chi_lookup, log_clo_lookup")
    print()
    print("!> Number of subdivisions in the log table interval.")
    print(f"integer, parameter :: log_ndiv = {LOG_NDIV}")
    print()
    print("!> Lower end of the log table interval, 11/16 = 0x1.6p-1 [nondim]")
    print(f"real, parameter :: log_table_start = {LOG_TABLE_START:.17g}")
    print()
    print(format_array("log_invc_lookup", invc,
                       "!> Lookup table of 1 / c for log_repro() table interval centers [nondim]"))
    print()
    print(format_array("logc_lookup", logc,
                       "!> Lookup table of log(c) for log_repro() table interval centers [nondim]"))
    print()
    print(format_array("log_chi_lookup", chi,
                       "!> Lookup table of high parts of c for log_repro() table interval centers [nondim]"))
    print()
    print(format_array("log_clo_lookup", clo,
                       "!> Lookup table of low parts of c for log_repro() table interval centers [nondim]"))
    print()
    print("end module MOM_log_data_n128")


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--precision", type=int, default=100,
                        help="decimal working precision")
    parser.add_argument("--search-radius", type=int, default=0,
                        help="number of 2**-43 log(c) grid points to search on each side")
    parser.add_argument("--objective", default="nearest-log",
                        choices=["nearest-log", "nearest-c", "nearest-chi", "smallest-clo"],
                        help="criterion for selecting among searched log(c) grid points")
    args = parser.parse_args()

    if EXP_STRIDE % LOG_NDIV != 0:
        raise SystemExit("LOG_NDIV must evenly divide one binary64 exponent stride")

    getcontext().prec = args.precision
    invc, logc, chi, clo = generate_tables(args.search_radius, args.objective)
    print_module(invc, logc, chi, clo, args.objective, args.search_radius)


if __name__ == "__main__":
    main()
