name: Decomposition

on: [push, pull_request]

jobs:
  build-test-layout:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .testing

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive

    - uses: ./.github/actions/testing-setup

    - name: Create validation data
      run: make run.symmetric -k -s

    - name: Test layout
      run: make test.layouts -k -s
