name: MacOS Stencil related verification

on: [push, pull_request]

jobs:
  test-macos-symmetric-layout-rotation:

    runs-on: macOS-latest

    # TODO: Move these to the macos config file?
    env:
      CC: gcc-11
      FC: gfortran-11

    defaults:
      run:
        working-directory: .testing

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive

    - uses: ./.github/actions/macos-setup

    - name: Compile MOM6 in asymmetric memory mode
      run: make build/asymmetric/MOM6 -j

    - name: Create validation data
      run: make run.symmetric -k -s

    - name: Run tests
      run: make test.grid test.layout test.rotate -k -s
