name: OpenMP

on: [push, pull_request]

jobs:
  build-test-openmp:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .testing

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive

    - uses: ./.github/actions/testing-setup

    - name: Compile with openMP
      run: make build/openmp/MOM6 -j

    - name: Create validation data
      run: make run.symmetric -k -s

    - name: Test openMP
      run: make test.openmps -k -s
