name: Reproducing optimization

on: [push, pull_request]

jobs:
  build-test-repro:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .testing

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive

    - uses: ./.github/actions/testing-setup

    - name: Compile MOM6 using repro optimization
      run: make build/repro/MOM6 -j

    - name: Create validation data
      run: make run.symmetric -k -s

    - name: Test optimization
      run: make test.repros -k -s
