name: Rotational symmetry

on: [push, pull_request]

jobs:
  build-test-rotation:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .testing

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive

    - uses: ./.github/actions/testing-setup

    - name: Create validation data
      run: make run.symmetric -k -s

    - name: Test rotation
      run: make test.rotations -k -s
