name: Code style

on: [push, pull_request]

jobs:
  check-style:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Check white space
      run: ./.testing/trailer.py -e TEOS10 -l 120 src config_src
